---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubewatch
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - pods
  - namespaces
  - services
  - deployments
  - replicationcontrollers
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watchhorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: default
